"""Project software-requirements adapter.

Generated by `/trace-matrix init`-driven authoring under task ben/049 on
2026-05-12, after Read of the three SRS source docs:

  - docs/project/dhfs/pca-device/design-controls/requirements/software-requirements.md
  - docs/project/dhfs/connectivity-adapter/design-controls/requirements/software-requirements.md
  - docs/project/dhfs/cloud-suite/design-controls/requirements/software-requirements.md

All three docs share the medtech-docs convention column shape used by the
default design_inputs parser, with two SW-specific changes:

  - the ID column is `SW ID` (not `DI ID`)
  - the upstream-trace column is `Traces to DI` (not `Traces to UN`)

The verification-method column is unchanged from DI shape, but the V&V
layer is still built from the DI doc's verification column for these three
DHFs (the DI->VER edges already exist; SW->VER edges are emitted by this
adapter when a VER-* token is present in the SW row's Verification Method
cell, giving the trace matrix SW->VER edges where present).

This adapter is the project-side override for the `software` layer key in
`trace-matrix.yml` for any DHF whose SRS uses the convention above. Shared
across all three system DHFs (pca-device, connectivity-adapter,
cloud-suite). Module/item DHFs sourced from Jira mirrors continue to use
the shared `jira-mirror` adapter via the `adapter:` key in
`trace-matrix.yml`.

Default behavior in the shipped `parsers/defaults/software.py` is a no-op
because many DHFs trace directly DI->V&V. For DHFs with a populated SRS
this override produces the SW layer.
"""
from __future__ import annotations

import re
from pathlib import Path

from adapter_api import ParserResult
from parsers.markdown_table import parse_file


_GROUP_RE = re.compile(r"^([A-Z]\d+)\b")
_DEFAULT_VER_RE = re.compile(r"\b(VER-[A-Z0-9][A-Z0-9-]+)\b")
_CRIT_NORMALIZE = {
    "CTS": "CtS",
    "CTF": "CtF",
    "CTC": "CtC",
    "CTP": "CtP",
    "S": "Supporting",
}


def _summarize(text: str, max_chars: int = 90) -> str:
    text = text.strip()
    if len(text) <= max_chars:
        return text
    cut = text[:max_chars].rsplit(" ", 1)[0]
    return cut + "…"


def _strip_md_emphasis(s: str) -> str:
    return s.replace("**", "").replace("*", "").strip()


def _split_ids(s: str) -> list[str]:
    return [tok.strip() for tok in re.split(r"[,;]", s) if tok.strip()]


def parse(path: Path, layer_cfg: dict) -> ParserResult:
    id_prefix = layer_cfg.get("id_prefix", "SW")
    cols = layer_cfg.get("columns", {})
    id_col = cols.get("id", f"{id_prefix} ID")
    stmt_col = cols.get("statement", "Requirement Statement")
    traces_col = cols.get("traces_up", "Traces to DI")
    verif_col = cols.get("verification", "Verification Method")
    crit_col = cols.get("criticality", "Criticality")
    accept_col = cols.get("acceptance", "Acceptance Criteria")

    ver_pattern = layer_cfg.get("ver_id_pattern")
    ver_re = re.compile(ver_pattern) if ver_pattern else _DEFAULT_VER_RE

    if not path or not path.exists():
        return ParserResult(warnings=[f"source missing: {path}"])

    nodes: list[dict] = []
    warnings: list[str] = []

    for table in parse_file(path):
        if id_col not in table.headers:
            continue
        group_label = table.section or ""
        group_match = _GROUP_RE.match(group_label)
        group = group_match.group(1) if group_match else None

        for row in table.rows:
            sid = row.get(id_col, "").strip()
            if not sid.startswith(id_prefix + "-"):
                continue
            statement = row.get(stmt_col, "").strip()
            traces_di = _split_ids(row.get(traces_col, ""))
            ver_text = row.get(verif_col, "")
            ver_ids = ver_re.findall(ver_text)

            crit_raw = _strip_md_emphasis(row.get(crit_col, ""))
            crit = _CRIT_NORMALIZE.get(crit_raw.upper()) if crit_raw else None

            nodes.append(
                {
                    "id": sid,
                    "summary": _summarize(statement),
                    "full_text": statement,
                    "category": row.get("Category", "").strip() or None,
                    "criticality": crit,
                    "group": group,
                    "group_label": group_label or None,
                    "acceptance_criteria": row.get(accept_col, "").strip() or None,
                    "verification_method": ver_text.strip() or None,
                    "traces_forward_ids": list(traces_di),
                    "verification_ids": list(ver_ids),
                    "has_verification_id": bool(ver_ids),
                }
            )

    return ParserResult(nodes=nodes, warnings=warnings)
