"""Adapter API — the contract between the trace-matrix skill and per-project
adapters.

Every parser — whether it's a default shipped with the skill or a project-side
adapter generated by `/trace-matrix init` — implements the same tiny function:

    def parse(path: Path, layer_cfg: dict) -> ParserResult

The skill's build pipeline never cares whether a parser is default or
generated. `load_adapter()` handles the resolution rule:

    1. If `tools/project-console/trace-matrix/adapters/<layer>.py` exists,
       import it and use its `parse` function.
    2. Otherwise fall back to the skill-shipped default at
       `.claude/skills/trace-matrix/scripts/parsers/defaults/<layer>.py`.

This keeps the build deterministic (no LLM at build time). LLM/analysis work
happens only during `init`, which produces files on disk that subsequent
builds import directly.
"""
from __future__ import annotations

import importlib.util
import sys
from dataclasses import dataclass, field
from pathlib import Path
from types import ModuleType
from typing import Callable


# ---------------------------------------------------------------------------
# Node + ParserResult shape
# ---------------------------------------------------------------------------

# A Node is a plain dict (not a dataclass) so adapters can populate whatever
# optional fields they have without boilerplate. The required keys:
#
#   id                 : str       — the stable identifier (e.g. "UN-001")
#   summary            : str       — short one-line label (≤90 chars ideal)
#   full_text          : str       — the full requirement/need/module text
#   traces_forward_ids : list[str] — IDs in the layer this one traces into
#
# Optional keys that emit picks up if present:
#   category, criticality, group, group_label, stakeholder, priority,
#   source_ref, acceptance_criteria, verification_method, iec_class,
#   module_name, verification_ids (DI-specific)
#
# Adapters can put anything else in the dict — emit copies only known keys.


@dataclass
class ParserResult:
    """Return shape from every layer adapter.

    nodes    : the extracted trace nodes for this layer
    warnings : non-fatal parsing issues (stale rows, partial matches, etc.)
               Surfaced in build stdout and in the generated md deliverable.
    extras   : optional adapter-specific data (e.g. DI parser returns
               derived V&V nodes here under 'vnv_nodes')
    """
    nodes: list[dict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    extras: dict = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Rational check — does a parser result look plausible?
# ---------------------------------------------------------------------------


@dataclass
class RationalCheck:
    ok: bool
    reason: str
    node_count: int = 0
    prefix_ok: bool = False
    sample_ids: list[str] = field(default_factory=list)


def _prefix_matches(node_id: str, prefix: str) -> bool:
    """An ID belongs to a layer if it starts with the prefix and has
    additional characters after it. Accepts UN-001, M1, SR-01, DI_014, etc.
    """
    if not node_id.startswith(prefix):
        return False
    rest = node_id[len(prefix):]
    return bool(rest) and (rest[0] in "-_" or rest[0].isdigit() or rest[0].isalpha())


def rational_check(
    result: ParserResult,
    id_prefix: str | None,
    *,
    source_present: bool = True,
    layer_key: str | None = None,
) -> RationalCheck:
    """Decide whether a parser produced plausible output.

    Called at init time to choose between default parser and adapter
    generation. A pass means the default parser works well enough; a fail
    triggers the LLM-powered adapter generation flow in `/trace-matrix init`.

    Special cases:
    - The V&V layer has no source of its own by default (it is derived
      from DI). Zero nodes there is not a parser failure — it means the
      pass-through adapter did its job and a project override is only
      needed if the project has a real verification-protocols doc.
    - When `source_present=False`, zero nodes means the source file is
      missing or empty. That's a *data* gap, not an adapter gap — no
      generated adapter can conjure content out of nothing. Reported as
      "source_empty" rather than a fail.

    Otherwise:
    - zero nodes with a present source → fail
    - all node IDs match the expected prefix → pass
    - ≥80% match → pass with note
    - anything else → fail
    """
    count = len(result.nodes)

    if layer_key == "vnv" and not source_present:
        return RationalCheck(
            ok=True,
            reason="V&V pass-through (DI-derived); override only if a real protocols doc exists",
            node_count=count,
            prefix_ok=True,
        )

    if count == 0:
        if not source_present:
            return RationalCheck(
                ok=True,
                reason="source_empty — no adapter can help",
                node_count=0,
                prefix_ok=True,
            )
        return RationalCheck(ok=False, reason="parser returned zero nodes from a present source")

    sample = [n.get("id", "") for n in result.nodes[:5]]

    if not id_prefix:
        return RationalCheck(ok=True, reason="no prefix configured; accepting",
                             node_count=count, prefix_ok=True, sample_ids=sample)

    matches = sum(1 for n in result.nodes if _prefix_matches(n.get("id", ""), id_prefix))
    ratio = matches / count

    if ratio >= 1.0:
        return RationalCheck(ok=True, reason=f"all {count} nodes match prefix '{id_prefix}'",
                             node_count=count, prefix_ok=True, sample_ids=sample)
    if ratio >= 0.8:
        return RationalCheck(
            ok=True,
            reason=f"{matches}/{count} nodes match prefix '{id_prefix}' (acceptable)",
            node_count=count, prefix_ok=True, sample_ids=sample,
        )
    return RationalCheck(
        ok=False,
        reason=f"only {matches}/{count} nodes match prefix '{id_prefix}' — default parser likely wrong",
        node_count=count, prefix_ok=False, sample_ids=sample,
    )


# ---------------------------------------------------------------------------
# Adapter resolution — project override vs skill default
# ---------------------------------------------------------------------------

# Where per-project generated adapters live. Set by explicit user direction
# ("stored in the console"). Paths are resolved from the repo root.
PROJECT_ADAPTERS_REL = Path("tools") / "project-console" / "trace-matrix" / "adapters"


def project_adapter_path(repo_root: Path, layer_key: str) -> Path:
    return repo_root / PROJECT_ADAPTERS_REL / f"{layer_key}.py"


def default_adapter_path(skill_dir: Path, layer_key: str) -> Path:
    return skill_dir / "scripts" / "parsers" / "defaults" / f"{layer_key}.py"


def _load_python_file(path: Path, module_name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(module_name, path)
    if spec is None or spec.loader is None:
        raise ImportError(f"cannot load {path}")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod
    spec.loader.exec_module(mod)
    return mod


def load_adapter(
    layer_key: str,
    repo_root: Path,
    skill_dir: Path,
) -> tuple[Callable, str]:
    """Resolve the parse() function for a layer.

    Returns (parse_callable, source_label) where source_label is one of:
      - "project: <path>"  if a project adapter exists
      - "default: <path>"  if falling back to the skill default
    """
    proj = project_adapter_path(repo_root, layer_key)
    if proj.is_file():
        mod = _load_python_file(proj, f"tm_project_adapter_{layer_key}")
        return mod.parse, f"project: {proj.relative_to(repo_root)}"

    dflt = default_adapter_path(skill_dir, layer_key)
    if dflt.is_file():
        mod = _load_python_file(dflt, f"tm_default_adapter_{layer_key}")
        return mod.parse, f"default: {dflt.name}"

    raise FileNotFoundError(
        f"No adapter found for layer '{layer_key}' — "
        f"checked {proj} and {dflt}"
    )
