"""JSON sidecar + markdown deliverable emitters."""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone
from pathlib import Path

from graph import TraceGraph


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    os.replace(tmp, path)


def to_sidecar(dhf: str, graph: TraceGraph) -> dict:
    """Convert the in-memory graph to the JSON sidecar shape (v1.1)."""
    layers_out = []
    for layer in graph.layers:
        items_out = []
        for it in layer.items:
            items_out.append(
                {
                    "id": it["id"],
                    "summary": it.get("summary") or "",
                    "full_text": it.get("full_text") or "",
                    "category": it.get("category"),
                    "criticality": it.get("criticality"),
                    "group": it.get("group"),
                    "group_label": it.get("group_label"),
                    "stakeholder": it.get("stakeholder"),
                    "priority": it.get("priority"),
                    "source_ref": it.get("source_ref"),
                    "acceptance_criteria": it.get("acceptance_criteria"),
                    "verification_method": it.get("verification_method"),
                    "iec_class": it.get("iec_class"),
                    "module_name": it.get("module_name"),
                    "traces_forward": it.get("traces_forward", []),
                    "traces_reverse": it.get("traces_reverse", []),
                }
            )
        layers_out.append(
            {
                "key": layer.key,
                "title": layer.title,
                "id_prefix": layer.id_prefix,
                "source_files": layer.source_files,
                "items": items_out,
                "missing_reason": layer.missing_reason,
                "edges_known": layer.edges_known,
                "warnings": layer.warnings,
            }
        )

    return {
        "version": "1.1",
        "dhf": dhf,
        "generated_at": _now_iso(),
        "layers": layers_out,
        "edges": graph.edges,
        "gaps": graph.gaps,
        "stats": graph.stats,
    }


def write_json(path: Path, sidecar: dict) -> None:
    _atomic_write(path, json.dumps(sidecar, indent=2, ensure_ascii=False) + "\n")


def write_markdown(path: Path, sidecar: dict) -> None:
    """Render a controlled markdown deliverable for the DHF."""
    out: list[str] = []
    dhf = sidecar["dhf"]
    out.append(f"# Trace Matrix — {dhf}")
    out.append("")
    out.append(f"> _Generated by `trace-matrix` skill at {sidecar['generated_at']} (sidecar v{sidecar['version']})._")
    out.append("> _Regenerated by the skill; do not hand-edit._")
    out.append("")

    out.append("## Summary")
    out.append("")
    out.append("| Layer | Count | With Forward | With Reverse | Orphans | Notes |")
    out.append("|---|---:|---:|---:|---:|---|")
    for layer in sidecar["layers"]:
        s = sidecar["stats"].get(layer["key"], {})
        notes = []
        if layer["missing_reason"]:
            notes.append(f"_{layer['missing_reason']}_")
        if layer["key"] == "architecture" and not layer["edges_known"]:
            notes.append("_module ↔ DI mapping not yet captured_")
        out.append(
            f"| {layer['title']} | {s.get('count', 0)} | {s.get('with_forward', 0)} | "
            f"{s.get('with_reverse', 0)} | {s.get('orphan', 0)} | {' '.join(notes)} |"
        )
    out.append("")

    if sidecar["gaps"]["broken_refs"]:
        out.append("## Broken References")
        out.append("")
        for br in sidecar["gaps"]["broken_refs"]:
            out.append(f"- `{br['from']}` → `{br['to']}` ({br['reason']})")
        out.append("")

    for layer in sidecar["layers"]:
        out.append(f"## {layer['title']}")
        if layer["missing_reason"]:
            out.append("")
            out.append(f"> ⚠️ Layer source missing — `{layer['missing_reason']}`")
            out.append("")
            continue
        if layer["key"] == "architecture" and not layer["edges_known"]:
            out.append("")
            out.append("> ⚠️ Module ↔ DI mapping table not present in architecture source; modules render without forward edges.")
            out.append("")
        if not layer["items"]:
            out.append("")
            out.append("_No items found._")
            out.append("")
            continue

        out.append("")
        out.append("| ID | Summary | Criticality | Forward Traces | Reverse Traces |")
        out.append("|---|---|---|---|---|")
        for it in layer["items"]:
            fwd = ", ".join(f"`{t['id']}`" for t in it["traces_forward"]) or "—"
            rev = ", ".join(f"`{t['id']}`" for t in it["traces_reverse"]) or "—"
            crit = it.get("criticality") or "—"
            out.append(f"| `{it['id']}` | {it['summary']} | {crit} | {fwd} | {rev} |")
        out.append("")

    _atomic_write(path, "\n".join(out))
