#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Regenerate the auto-generated grounding block in an advisor agent file.

The grounding block is delimited by HTML comment markers so the renderer can
safely replace it without touching the surrounding persona prose. The block
tells CC subagents how to ground themselves before answering: which globs to
read, what order, and what not to invent.

Usage:
    render-grounding.py --agent regulatory-affairs
    render-grounding.py --all
    render-grounding.py --all --dry-run

Exit codes:
    0 = no change (already in sync)
    1 = updated (or would be updated, under --dry-run)
    2 = error
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make `lib` importable when this script is run directly.
_SCRIPT_DIR = Path(__file__).resolve().parent
_SKILL_ROOT = _SCRIPT_DIR.parent
sys.path.insert(0, str(_SKILL_ROOT))

from lib.loader import DomainAgent, load_agent_file  # noqa: E402


BEGIN_MARKER = "<!-- BEGIN GROUNDING (auto-generated by /advisors sync — do not edit by hand) -->"
END_MARKER = "<!-- END GROUNDING -->"


def _render_block(agent: DomainAgent) -> str:
    has_context = bool(agent.context)
    has_sources = bool(agent.sources)

    if not has_context and not has_sources:
        all_patterns = "_(no grounding sources configured — answers will rely on general knowledge only)_"
    else:
        all_patterns = ""

    context_section = ""
    if has_context:
        context_patterns = "\n".join(f"- `{g}`" for g in agent.context)
        context_section = f"""
### Context (always read)

These are foundational project documents that frame every answer. `Glob`
and `Read` all of them **before** looking at the user's question. They
establish the module architecture, regulatory strategy, scope boundaries,
and key decisions the program has already made.

{context_patterns}
"""

    sources_section = ""
    if has_sources:
        source_patterns = "\n".join(f"- `{g}`" for g in agent.sources)
        sources_section = f"""
### Sources (triage per question)

These contain domain knowledge triaged based on the user's question. Do
**not** read all of them — use the triage workflow below to select the
relevant files.

{source_patterns}
"""

    excludes = ""
    if agent.excludes:
        excludes_list = "\n".join(f"- `{g}`" for g in agent.excludes)
        excludes = f"\nExclude paths matching:\n{excludes_list}\n"

    return f"""{BEGIN_MARKER}

## Grounding Sources

Before answering any substantive question, you MUST ground yourself in the
project's authoritative documents. Cite file paths in your answer so the
user can verify every claim.
{all_patterns}{context_section}{sources_section}{excludes}

### Workflow

Treat discovery as context-first, then triage the rest.

1. **Context pass (always, before reading the question).** `Glob` and
   `Read` every file matching the Context patterns above. These are
   foundational — they establish module architecture, regulatory strategy,
   scope, and decisions the program has already made. Do this on every
   invocation regardless of the question.
2. Read the question. Identify which Sources patterns are relevant. Not
   every pattern needs to be consulted on every question.
3. Triage the Sources — run these signals in parallel and take the
   **union** of what they nominate as candidates:
   a. `Glob` the pattern and skim filenames. Descriptive filenames
      (e.g., `pccp-ai-final-2023.md`, `iec-62304-requirements.md`) often
      tell you directly whether a file is relevant.
   b. If the pattern's directory has a `README.md` or `INDEX.md`, `Read`
      it. Index files catalog or summarize contents and surface files
      whose filenames are opaque.
4. If the union is still too broad or ambiguous, use `Grep` as a
   disambiguator. Choose keywords from the **concepts** in the question —
   domain terms, synonyms, identifiers — not literal verbs from the user's
   wording. For regulatory questions that means terms like `predicate`,
   `substantially equivalent`, `K[0-9]{{6}}`, `510(k)`, standards clause
   numbers, named guidances. Use 2–4 terms per pass, not one.
5. `Read` every file that survived triage. Read as many as you need — the
   right number is whatever it takes to answer confidently and cite, not a
   fixed count. A scoping question may need 3 files; a cross-cutting
   comparison may need 15. The subagent runs in its own context window, so
   deep reading does not pollute the main thread.
6. Cross-reference the Context docs (step 1) with the Source docs
   (step 5) and cite file paths inline using backticks:
   `path/to/file.md`. Every substantive claim should be traceable to a
   file you actually read.
7. **External lookup pass (when warranted).** If the local grounding is
   thin, if the question calls for precedent or examples that wouldn't
   live in the project repo, or if an external identifier needs
   confirmation (K-number, guidance title, standard clause), use
   `WebFetch` against authoritative sources only — `fda.gov`, `iso.org`,
   `iec.ch`, `ansi.org`, `ema.europa.eu`, peer-reviewed journals. Cite
   fetched URLs alongside local file paths. Do not troll blogs, vendor
   marketing, or unverified aggregators. Prefer local grounding when it
   covers the question — the local docs reflect decisions the program
   has already made.
8. **Counterpoint pass.** Before finalizing, take one deliberate pass
   asking: what would a skeptical reviewer push back on? What alternative
   framings are live? What assumptions am I making that could fail? For
   regulatory work specifically, imagine an FDA reviewer reading this —
   where would they object? Surface the strongest 1–3 counterpoints as a
   short "Counterpoints & considerations" section at the end of your
   answer. Skip this pass for purely factual lookups, but apply it to any
   strategic, scoping, classification, or trade-off question. The goal is
   not to undermine your own answer — it is to make sure the user gets
   the trade-offs instead of false confidence.
9. If after triage the grounding is thin, contradictory, or silent on the
   question, say so explicitly rather than filling gaps with invention.
   Under-answering with citations beats over-answering without them.

### Hard rules

- Do **not** invent FDA interactions, clearance numbers (K-numbers), guidance
  document titles, standard clause numbers, or regulatory positions that are
  not present in the grounding sources.
- Do **not** commit the program to a regulatory position. You are an advisor
  supporting the team's thinking, not a decision-maker.
- Do **not** rubber-stamp the user's framing on strategic questions. Surface
  counterpoints even when the user seems committed to a direction — your job
  is to sharpen their thinking, not confirm it.
- If asked about something outside the grounding patterns above, acknowledge
  the limit and suggest the user consult the relevant human lead or a
  differently-scoped advisor.

{END_MARKER}"""


def _replace_block(body: str, new_block: str) -> tuple[str, bool]:
    """Insert or replace the grounding block in a body string.

    Returns (new_body, changed)."""
    if BEGIN_MARKER in body:
        if END_MARKER not in body:
            raise ValueError(
                f"found {BEGIN_MARKER!r} but no matching {END_MARKER!r}"
            )
        pre, rest = body.split(BEGIN_MARKER, 1)
        _, post = rest.split(END_MARKER, 1)
        # Strip trailing whitespace from pre so we don't accumulate blank lines
        new_body = pre.rstrip() + "\n\n" + new_block + post
    else:
        # Append to the end with a separator
        new_body = body.rstrip() + "\n\n" + new_block + "\n"

    return new_body, new_body != body


def _process_file(path: Path, dry_run: bool) -> bool:
    """Render grounding for one agent file. Returns True if content changed."""
    agent = load_agent_file(path)
    raw = path.read_text(encoding="utf-8")
    new_block = _render_block(agent)
    new_raw, changed = _replace_block(raw, new_block)
    if changed and not dry_run:
        path.write_text(new_raw, encoding="utf-8")
    return changed


def _resolve_agent_dirs(project_root: Path) -> list[Path]:
    dirs: list[Path] = []
    installed = project_root / ".claude" / "agents"
    if installed.exists():
        dirs.append(installed)
    bundled = _SKILL_ROOT / "agents"
    if bundled.exists():
        dirs.append(bundled)
    return dirs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--agent",
        help="Render only the named agent (looked up in .claude/agents/ then skill bundle)",
    )
    parser.add_argument("--all", action="store_true", help="Render every agent")
    parser.add_argument("--dry-run", action="store_true", help="Do not write")
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root (default: cwd)",
    )
    args = parser.parse_args()

    if not args.agent and not args.all:
        parser.error("specify --agent <name> or --all")

    dirs = _resolve_agent_dirs(args.project_root)
    if not dirs:
        print("error: no agent directories found", file=sys.stderr)
        return 2

    targets: list[Path] = []
    if args.agent:
        for d in dirs:
            candidate = d / f"{args.agent}.md"
            if candidate.exists():
                targets.append(candidate)
                break
        if not targets:
            print(f"error: agent '{args.agent}' not found", file=sys.stderr)
            return 2
    else:
        seen_names: set[str] = set()
        for d in dirs:
            for path in sorted(d.glob("*.md")):
                if path.stem in seen_names:
                    continue
                seen_names.add(path.stem)
                targets.append(path)

    any_changed = False
    for path in targets:
        try:
            changed = _process_file(path, dry_run=args.dry_run)
        except Exception as e:
            # Under --all, skip files that aren't advisor agents (e.g. plain
            # CC agents without frontmatter). Under --agent, fail hard.
            if args.all:
                print(f"skipped: {path} ({e})")
                continue
            print(f"error: {path}: {e}", file=sys.stderr)
            return 2
        status = (
            "would update" if (changed and args.dry_run)
            else "updated" if changed
            else "unchanged"
        )
        print(f"{status}: {path}")
        any_changed = any_changed or changed

    return 1 if any_changed else 0


if __name__ == "__main__":
    sys.exit(main())
