#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["pyyaml"]
# ///
"""Regenerate the auto-generated grounding block in an advisor agent file.

The grounding block is delimited by HTML comment markers so the renderer can
safely replace it without touching the surrounding persona prose. The block
tells CC subagents how to ground themselves before answering: which globs to
read, what order, and what not to invent.

Usage:
    render-grounding.py --agent regulatory-affairs
    render-grounding.py --all
    render-grounding.py --all --dry-run

Exit codes:
    0 = no change (already in sync)
    1 = updated (or would be updated, under --dry-run)
    2 = error
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Make `lib` importable when this script is run directly.
_SCRIPT_DIR = Path(__file__).resolve().parent
_SKILL_ROOT = _SCRIPT_DIR.parent
sys.path.insert(0, str(_SKILL_ROOT))

from lib.loader import DomainAgent, load_agent_file  # noqa: E402

try:
    import yaml
except ImportError:
    yaml = None  # only required for canonical-role mode


BEGIN_MARKER = "<!-- BEGIN GROUNDING (auto-generated by /advisors sync — do not edit by hand) -->"
END_MARKER = "<!-- END GROUNDING -->"

# Sibling-skill path: canonical-role descriptions live in /dhf-manifest's registry.
# Used only in canonical-role mode.
_CANONICAL_ROLES_PATH = (
    _SKILL_ROOT.parent / "dhf-manifest" / "data" / "canonical-roles.yaml"
)


_role_registry_cache: dict | None = None


def _load_role_registry() -> dict:
    """Load the L1+L2 canonical-role registry from the dhf-manifest skill.
    Returns the parsed `roles:` dict; raises if the file is missing or yaml
    isn't available."""
    global _role_registry_cache
    if _role_registry_cache is not None:
        return _role_registry_cache
    if yaml is None:
        raise RuntimeError(
            "canonical-role mode requires pyyaml; install with `pip install pyyaml`"
        )
    if not _CANONICAL_ROLES_PATH.exists():
        raise FileNotFoundError(
            f"canonical-role registry not found: {_CANONICAL_ROLES_PATH}\n"
            f"(the /dhf-manifest skill must be installed alongside /advisors)"
        )
    data = yaml.safe_load(_CANONICAL_ROLES_PATH.read_text(encoding="utf-8")) or {}
    _role_registry_cache = data.get("roles") or {}
    return _role_registry_cache


def _format_selector(entry: dict) -> str:
    """Format a yaml-native selector (dhfs/submissions) for inline display.
    Returns a parenthetical suffix string, or empty string if no selector."""
    parts = []
    if "dhfs" in entry:
        sel = entry["dhfs"]
        if isinstance(sel, dict):
            parts.append("dhfs where " + ", ".join(f"{k}={v!r}" for k, v in sel.items()))
        elif sel == "all":
            parts.append("all dhfs")
        else:
            parts.append(f"dhfs={sel!r}")
    if "submissions" in entry:
        sel = entry["submissions"]
        if sel == "all":
            parts.append("all submissions")
        else:
            parts.append(f"submissions={sel!r}")
    return f" ({'; '.join(parts)})" if parts else ""


def _render_canonical_role_block(agent: DomainAgent) -> str:
    """Render the 3-tier grounding block for canonical-role-mode agents.

    Reads `agent.canonical_roles.{tier_1, tier_2, tier_3}` from the agent's
    frontmatter and the role descriptions from the dhf-manifest skill's
    canonical-roles.yaml registry. Emits a project-agnostic body that
    references role names + a project-side discovery index — no literal globs.
    """
    cr = agent.canonical_roles or {}
    tier_1 = cr.get("tier_1") or []
    tier_2 = cr.get("tier_2") or []
    tier_3 = cr.get("tier_3") or {}
    researcher = tier_3.get("researcher") if isinstance(tier_3, dict) else None

    registry = _load_role_registry()

    def _desc(role_name: str) -> str:
        r = registry.get(role_name) or {}
        return r.get("description") or "(no description in registry)"

    def _render_tier_entries(entries: list, *, include_descriptions: bool) -> str:
        lines = []
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            role_name = entry.get("role")
            if not role_name:
                continue
            selector = _format_selector(entry)
            if include_descriptions:
                lines.append(f"- `{role_name}`{selector} — {_desc(role_name)}")
            else:
                lines.append(f"- `{role_name}`{selector}")
        return "\n".join(lines) if lines else "_(no roles declared)_"

    tier_1_list = _render_tier_entries(tier_1, include_descriptions=True)
    tier_2_list = _render_tier_entries(tier_2, include_descriptions=True)

    tier_3_section = ""
    if researcher:
        tier_3_section = f"""

### Semantic file locator (Tier 2 accelerator / Tier 3 fast path)

If `mcp__file-locator__locate` is available in your tool set, you have a
fourth retrieval mode alongside the discovery index (structural lookup),
`Grep` (literal token), and `Glob` (everything-of-a-kind): **semantic
file search** over the project's indexed docs. Call `locate(query,
k=10)` with a natural-language description of what you're looking for
when (a) Tier 2 index triage doesn't surface an obvious file, or (b) the
question references a topic, argument, or term you can't map to a
canonical role — reach for this *before* spinning up the heavier
`{researcher}` subagent. The locator returns ranked `(path, summary,
heading_anchor?, score)` hits grouped by confidence band, with a
`reasoning_hint`. It is a discovery aid, not a substitute for Tier 1
required reads.

**Read-count rubric for locator results.** Read the **top-ranked hit in
full**. If it answers the question, stop. If it partially answers, read
the next hit whose summary covers the missing angle. **Stop at 3 reads
unless the question is inherently multi-source** (e.g., "compare X
across all DHFs", "every place we argue Y") — the response's
`reasoning_hint` flags the multi-source case. After 3 reads without a
confident answer, fall through to the `{researcher}` subagent or surface
the gap to the user rather than reading further down a low-confidence
list. If `mcp__file-locator__locate` is not in your tool set, skip this
— the project hasn't installed the locator, and Tier 2 + Tier 3 cover
the same ground.

### Tier 3 — Independent search via researcher subagent

When Tier 1 + Tier 2 don't yield a confident, well-cited answer — for
example, the question touches a topic the discovery index hasn't
cataloged, references a project artifact you haven't seen, or your
triage produced gaps that meaningfully affect the answer — invoke the
`{researcher}` subagent via the `Agent` tool.

The researcher's job is exploratory file-finding: walk READMEs, follow
cross-references, glob/grep the project filesystem, return a curated
list of `(path, why-relevant)` pairs. It does NOT return raw file
contents and does NOT provide domain advice. You then `Read` the
recommended paths directly and incorporate them into your answer.

**When to invoke the researcher:**
- The question references a topic, document, or concept your Tier 1+2
  grounding doesn't cover.
- The discovery index has `null` resolutions or `informational` gaps for
  roles relevant to the question.
- Your triage of Tier 2 produced fewer relevant files than you'd expect
  for the question's complexity.
- You're about to give an answer with thin or no citations — pause and
  invoke the researcher first.

**When NOT to invoke the researcher:**
- The question is fully answerable from Tier 1 alone.
- The question is purely external (e.g., "what does FDA guidance X say?")
  — use `WebFetch` directly instead.
- You've already invoked the researcher and it returned empty — calling
  it again on the same topic won't help.

**Hint multi-file roles to the researcher.** When Tier 2 includes
`multi_file` roles (folder-pointer entries in the discovery index), the
relevant folders make excellent `hints` for the researcher prompt — it
narrows the search space to the right region of the tree.

**How to invoke:**

```
Agent(
  subagent_type: "{researcher}",
  description: "Find <topic> grounding",
  prompt: \"\"\"
    Topic: <distilled topic from the user's question>
    Project root: <absolute path>
    Already read: [<list of paths from your Tier 1+2 reads>]
    Optional hints: [<subtrees to focus on>, <keywords to grep>]

    Return a curated list of (path, why-relevant, ~size) tuples for
    files I should Read to ground my answer on this topic.
  \"\"\"
)
```

**Subagent-recursion limitation.** When this agent is itself invoked as
a nested subagent (e.g., from another agent's `Agent` tool call), Claude
Code does not pass the `Agent` tool down. In that nested context the
`{researcher}` subagent cannot be invoked. Fall back to performing the
researcher's workflow inline: `Glob` the topic's likely subtree, `Read`
the folder's `README.md`, follow cross-references, `Grep` for the
distilled topic terms, then `Read` the relevant files directly. This
fallback is functionally equivalent — only slower and without the
context-isolation benefit of the subagent call."""

    return f"""{BEGIN_MARKER}

## Grounding Sources

Before answering any substantive question, you MUST ground yourself in the
project's authoritative documents. Cite file paths in your answer so the
user can verify every claim.

This agent uses **three-tier canonical-role grounding**:

- **Tier 1 — Required grounding.** A small set of foundational documents
  loaded on EVERY invocation, in full, regardless of size. Non-negotiable.
- **Tier 2 — Index-driven discovery.** The `/dhf-manifest discovery-index`
  output catalogs question-relevant canonical roles; the agent picks the
  ones the question touches and `Read`s them.
- **Tier 3 — Independent search (researcher subagent).** When Tier 1 + Tier 2
  don't yield a confident, well-cited answer, invoke the
  `{researcher or 'advisor-researcher'}` subagent to explore the project filesystem for
  additional grounding (README walks, cross-reference following, grep on
  unfamiliar terms).

Canonical role names map to concrete file paths at runtime through the
per-project discovery index, so the same agent works across projects with
different folder conventions.

### Tier 1 — Required grounding (always read in full)

On every invocation, before reading the question:

1. **Read the discovery index** at
   `docs/project/dhf-manifest/<project-slug>-dhf-discovery.json`. The
   `<project-slug>` is the lowercased `project.yml` `project.name` with
   spaces and underscores replaced by hyphens (e.g., `My Project Name` →
   `my-project-name`). If you don't know the slug, `Glob` for
   `docs/project/dhf-manifest/*-dhf-discovery.json` and pick the match.
   - If the index is missing entirely, fall back to dynamic globbing per
     the patterns in `.claude/skills/dhf-manifest/data/canonical-roles.yaml`,
     and tell the user the index is regenerable via `/dhf-manifest
     discovery-index`.
   - If the index exists but a specific role's resolution is `null`,
     check the index's `gaps[]` entry for the reason. Continue without
     that source — record the gap in your answer.

2. **Read these canonical roles in full** as your required foundational
   grounding. Do this every invocation:

{tier_1_list}

   **Read each Tier 1 file in full.** Do NOT skip a Tier 1 file because
   its `tokens_estimate` is large. The model is configured with sufficient
   context window for the full Tier 1 set; `tokens_estimate` is
   informational only, not a runtime decision lever for the agent.

   **Tool-constraint accommodation.** The `Read` tool has a per-call cap
   (~25 K tokens). For Tier 1 files that exceed it, use **multiple
   `Read` calls with explicit non-overlapping line ranges that together
   cover the entire file**. Slicing across calls is acceptable; skipping
   sections is not. In your answer, when citing a Tier 1 file you read in
   slices, note this transparently (e.g., "read in 3 slices covering
   lines 1–1000, 1001–2000, 2001–2873"). Never use `Grep`-only as a
   substitute for required reads — Grep can guide reading but cannot
   replace it.

### QMS governance check (when analyzing or recommending changes to a governed doc)

For projects whose DHFs use `dhf_organization: external` with a
`.taxonomy.yml`, the discovery index attaches `governing_qms` to each
resolved per-DHF entry when the taxonomy declares it. If your analysis
will recommend changes to a document whose discovery-index entry carries
`governing_qms`, you MUST `Read` the governing QMS templates before
finalizing your recommendation — the QMS form is the controlling
authoring contract for that doctype, and a recommendation that
contradicts the form's column schema, scoring scales, or section
structure cannot be safely executed.

What to read:

- Every `forms[]` ID — these are document control templates (`FORM-NNNNNNNNN`),
  rendered as markdown under `docs/internal/source-md/Forms/`.
- The first `sops[]` and `work_instructions[]` ID — the parent process and
  refinement instructions. Subsequent entries are skim-only unless the
  question pivots on them.
- `upstream_inputs[]` IDs only when the question asks about how content
  flows INTO the doctype from another form.

If `governing_qms` is absent from the index entry, do NOT invent a
governing form — the taxonomy mapping is unverified for that doctype.
Flag the gap in your answer: _"This doctype's `.taxonomy.yml` mapping
does not declare `governing_qms` — recommendations are made against ISO/
IEC standards only; verify against QMS templates before authoring."_

Internal-mode DHFs (no `.taxonomy.yml`) do not carry `governing_qms` in
the index — use `qms-manifest.json` (sibling of `<slug>-dhf-manifest.json`)
to resolve governance instead. Each obligation there carries a
`qms_grounding.direct[]` list of QMS-ID anchors that links back to the
governing SOP/Form via the `qms-manifest.md` index.

### Tier 2 — Index-driven discovery (triage per question)

The discovery index already lists every triageable role and its resolved
path(s). Do **not** eagerly load any of these — pick the relevant ones
after reading the user's question.

Available roles in Tier 2:

{tier_2_list}

For each role in your Tier 2 declaration:
- **Single-file resolutions** (most roles): the index entry has a `path`
  field — `Read` that path.
- **Folder-pointer resolutions** (roles with `multi_file: true` in the
  registry, e.g., complaints / KOL feedback / literature search): the
  index entry has `folder` + `file_count` but no per-file paths. `Glob`
  inside the folder with question keywords + descriptive filename
  patterns, then `Read` the survivors. An empty folder (`file_count: 0`)
  is meaningful signal — note it explicitly in your answer.

If Tier 2 triage is still ambiguous, use `Grep` against the role's folder
with 2–4 concept terms from the question (domain terms, identifiers,
standards clause numbers) — not literal verbs from the user's wording.{tier_3_section}

### Workflow

Treat discovery as Tier-1-first, Tier-2-per-question, Tier-3-when-needed.

1. **Tier 1 pass (always, before reading the question).** Read the
   discovery index. Read every Tier 1 canonical role in full. If the index
   is missing, fall back to dynamic globbing once and note this to the
   user.

2. Read the question. Identify which Tier 2 roles are relevant.

3. **Tier 2 triage via the discovery index.** For each relevant role:
   - **Per-DHF roles**: the index's `dhf_roles` block lists each DHF's
     resolved path or folder pointer. `Read` only the DHFs the question
     touches.
   - **Per-submission roles**: pick the submission the question scopes
     to. Read the composition manifest first, then specific docs.
   - **Multi-file folder pointers**: `Glob` inside the folder with
     question keywords; `Read` the survivors.
   - **External-data roles**: the index gives `folder` + `file_count`
     but not per-file paths. `Glob` against the folder with descriptive
     filename patterns + question keywords; `Read` the survivors.

4. If Tier 2 triage is still ambiguous, use `Grep` against the role's
   folder with 2–4 concept terms from the question.

5. **Tier 3 — invoke the researcher if needed.** If Tier 1 + Tier 2 don't
   cover the question, invoke the researcher subagent (see Tier 3 section
   above), then `Read` its recommended paths.

6. Cross-reference Tier 1 (foundational) with Tier 2 + Tier 3 (triaged)
   and cite file paths inline using backticks: `path/to/file.md`. Every
   substantive claim must be traceable to a file you actually read.

7. **External lookup pass (when warranted).** If local grounding is thin,
   the question calls for precedent not in the project repo, or an
   external identifier needs confirmation (K-number, guidance title,
   standard clause), use `WebFetch` against authoritative sources only —
   `fda.gov`, `iso.org`, `iec.ch`, `ansi.org`, `ema.europa.eu`,
   peer-reviewed journals. Cite fetched URLs alongside local file paths.
   Do not troll blogs, vendor marketing, or unverified aggregators.

   **AI-friendly federal endpoints (preferred when reachable).** WebFetch
   against the `fda.gov` HTML site / direct media downloads is frequently
   blocked. Prefer these machine-readable endpoints when verifying CFR /
   FR-notice / FDA-database citations:
   - **eCFR API** — `https://www.ecfr.gov/api/versioner/v1/full/<date>/title-N.xml?chapter=...&subchapter=...&part=N`
     returns verbatim CFR text. The eCFR human viewer (`ecfr.gov/current/...`)
     redirects bots to a CAPTCHA wall — always use the `/api/` endpoint.
   - **Federal Register API** — `https://www.federalregister.gov/api/v1/documents.json?conditions[...]`
     finds FR notices; govinfo PDF URLs returned by the API (`govinfo.gov/content/pkg/...`)
     are downloadable.
   - **openFDA** — `https://api.fda.gov/` for adverse events, recalls, NDC,
     classifications. NOT for guidance-document text.
   When a needed source is on a blocked endpoint (e.g., `accessdata.fda.gov`
   pmn.cfm K-number records, `fda.gov/media/<id>/download` guidance PDFs),
   note the block, return `unverified` for the affected claim, and either
   recommend a `/web-control`-driven browser session or ask the user to
   download the PDF and place it under the appropriate `source/` folder
   for distillation.

8. **Citation verification pass.** Before vouching for any cited standards
   clause / CFR section / K-number / FDA-guidance reference in your
   answer, verify the citation. There are two modes — pick the one
   available in your current execution context:

   **Mode A — `citations` advisor dispatch (preferred when available).**
   If the `Agent` tool is in your toolset, invoke the `citations` advisor
   with the `(claim, reference_target)` pair. Quote the resulting verdict
   band (`sound | unverified | broken`) in your response footnote.

   **Mode B — Inline verification fallback (REQUIRED when `Agent` is not
   in your toolset).** Claude Code strips the `Agent` tool from subagent
   invocations as a recursion guard, so when you've been called as a
   subagent from another agent's `Agent` tool call, Mode A is unreachable
   regardless of what your frontmatter declares. In that context, perform
   the verification inline:
   - `Read` the L1a registry distillation file for the citation's
     category (under `.claude/skills/medtech-docs/references/<category>/`)
     and locate the specific clause / section / record. Honor quarantine
     banners and `[VERIFY]` markers — bannered content cannot support a
     `sound` verdict on a clause-number claim.
   - `Read` the L1b project applicability file (under
     `docs/external/<category>/`) and locate the corresponding entry.
   - **Escalate to the full text when the distillation isn't enough.**
     If the distillation is silent on the cited clause/section or the
     claim turns on exact wording: for FDA guidance, `Read` the bundled
     full text at `references/fda-guidance/source-md/<basename>.md`
     (strip any `-distilled` suffix); for CFR, fetch the live eCFR API
     (workflow step 7 endpoints); for ISO/IEC standards, no source
     exists locally — return `unverified` and say the standard itself
     is needed rather than inferring clause content. The distilled file
     remains the citation you name; the source-md/eCFR read is evidence.
   - Compare the cited claim's predicate against what the sources
     actually say. Predicate match = `sound`. Predicate mismatch
     (same clause number, different topic) = `broken`. Source silent /
     paywalled / fetch failure = `unverified`.
   - Quote the verdict band in your footnote and cite both L1a and L1b
     paths transparently.

   For either mode:
   - If `broken` — do NOT vouch; surface the defect with the suggested fix
     in your answer.
   - If `unverified` — note the unverified status explicitly; do not
     silently treat as `sound` by leaning on internal corroboration.
   - If `sound` — proceed; the citation is verified against L1a + L1b.

   Skip this step for intra-doc anchors, glossary terms, and informal
   cross-references — they're too cheap to gate and the cost would
   outweigh the value.

9. **Counterpoint pass.** Before finalizing, take one deliberate pass
   asking: what would a skeptical reviewer push back on? What alternative
   framings are live? What assumptions am I making that could fail?
   Surface the strongest 1–3 counterpoints as a short "Counterpoints &
   considerations" section at the end of your answer. Skip this pass for
   purely factual lookups; apply it to any strategic, scoping, or trade-off
   question.

10. If after Tier 1 + Tier 2 + Tier 3 the grounding is thin,
    contradictory, or silent on the question, say so explicitly rather
    than filling gaps with invention. Under-answering with citations
    beats over-answering without them.

### Hard rules

- **Tier 1 is required.** Read all Tier 1 canonical roles on every
  invocation. Do not skip based on file size. For files exceeding the
  `Read` tool's per-call cap (~25 K tokens), use multiple `Read` calls
  with explicit line ranges that together cover the entire file. Slicing
  is acceptable; skipping sections or using `Grep`-only as a substitute
  for required reads is not.
- **Cite both layers for external citations.** When citing a standards
  clause, CFR section, FDA guidance reference, or industry framework in
  your answer, cite BOTH the registry distillation file (under
  `.claude/skills/medtech-docs/references/<category>/<name>.md` — the
  L1a tier, surfaced via the `registry_*` canonical roles) AND the
  project applicability file (under `docs/external/<category>/<name>.md`
  — the L1b tier, surfaced via the existing `standards` / `fda_guidance`
  / `regulations` / `industry_frameworks` canonical roles) in your
  response footnotes. The registry distillation carries the authoritative
  source text — what the standard / regulation / guidance actually says.
  The project applicability file carries this program's decisions about
  how that source applies to this device. Citing only one layer leaves a
  one-sided citation that masks a verification gap. Use the `citations`
  advisor (workflow step 8) to enforce this on any reference you're
  about to vouch for.
- **The reference-consumption ladder has four rungs — climb in order.**
  (1) L1b project applicability (`docs/external/<category>/`) — what
  this program decided; (2) L1a registry distillation
  (`.claude/skills/medtech-docs/references/<category>/`) — what the
  source says, condensed; (3) the bundled full text
  (`references/<category>/source-md/<basename>.md`, currently
  fda-guidance only) — exact wording, omitted appendices, footnotes;
  (4) the open web (step 7's AI-friendly endpoints; live eCFR for CFR
  currency) — only when the local rungs can't answer. Never skip a rung
  downward (web before checking local tiers wastes effort and loses the
  program's decisions); never stop a rung short when the claim needs
  exact wording the distillation doesn't carry. ISO/IEC clause text is
  on no rung — it is paywalled and absent locally; say the standard is
  needed instead of inferring.
- Do **not** invent facts, identifiers, citations, or positions that are
  not present in the grounding sources.
- **Show the bytes before asserting a file's current state.** Do not claim
  something is *fixed*, *resolved*, *absent*, *clean*, or that it
  *contradicts a finding you were handed* unless you ran the check
  (`Read` / `Grep`) this pass and can quote the **literal matched line**
  (or report the exact pattern searched with "0 matches"). A bare "I
  re-grepped and confirmed" without the shown bytes is not evidence. An
  **absent / already-resolved** claim is the single highest-risk assertion:
  it can be confabulated from a strong prior, or inherited from an upstream
  completion claim (a task checkbox, a "swept clean" note, a "resolved"
  line) that was itself never verified — most dangerous exactly when the
  project has a strong *intended* state on the topic and you are tempted to
  report the intended state as the actual one. To **overturn or
  mark-resolved** a finding you were given, show the bytes. Reporting a
  problem you can point at does not need this guard; an absence/resolved
  claim always does.
- Do **not** commit the program to a position. You are an advisor
  supporting the team's thinking, not a decision-maker.
- Do **not** rubber-stamp the user's framing on strategic questions.
  Surface counterpoints even when the user seems committed to a
  direction — your job is to sharpen their thinking, not confirm it.
- If asked about something outside the canonical roles AND outside what
  the researcher can find via Tier 3, acknowledge the limit and suggest
  the user consult the relevant human lead or a differently-scoped
  advisor.
- Do **not** invent canonical role names. Use only the roles enumerated
  above and resolvable through the discovery index. If a role you need
  isn't in the index, either invoke the researcher (Tier 3) or flag the
  gap to the user.

{END_MARKER}"""


def _render_block(agent: DomainAgent) -> str:
    # Canonical-role mode: render the 3-tier grounding body.
    if agent.is_canonical_role_mode:
        return _render_canonical_role_block(agent)

    # Legacy literal-glob mode (unchanged).
    has_context = bool(agent.context)
    has_sources = bool(agent.sources)

    if not has_context and not has_sources:
        all_patterns = "_(no grounding sources configured — answers will rely on general knowledge only)_"
    else:
        all_patterns = ""

    context_section = ""
    if has_context:
        context_patterns = "\n".join(f"- `{g}`" for g in agent.context)
        context_section = f"""
### Context (always read)

These are foundational project documents that frame every answer. `Glob`
and `Read` all of them **before** looking at the user's question. They
establish the module architecture, regulatory strategy, scope boundaries,
and key decisions the program has already made.

{context_patterns}
"""

    sources_section = ""
    if has_sources:
        source_patterns = "\n".join(f"- `{g}`" for g in agent.sources)
        sources_section = f"""
### Sources (triage per question)

These contain domain knowledge triaged based on the user's question. Do
**not** read all of them — use the triage workflow below to select the
relevant files.

{source_patterns}
"""

    excludes = ""
    if agent.excludes:
        excludes_list = "\n".join(f"- `{g}`" for g in agent.excludes)
        excludes = f"\nExclude paths matching:\n{excludes_list}\n"

    return f"""{BEGIN_MARKER}

## Grounding Sources

Before answering any substantive question, you MUST ground yourself in the
project's authoritative documents. Cite file paths in your answer so the
user can verify every claim.
{all_patterns}{context_section}{sources_section}{excludes}

### Workflow

Treat discovery as context-first, then triage the rest.

1. **Context pass (always, before reading the question).** `Glob` and
   `Read` every file matching the Context patterns above. These are
   foundational — they establish module architecture, regulatory strategy,
   scope, and decisions the program has already made. Do this on every
   invocation regardless of the question.
2. Read the question. Identify which Sources patterns are relevant. Not
   every pattern needs to be consulted on every question.
3. Triage the Sources — run these signals in parallel and take the
   **union** of what they nominate as candidates:
   a. `Glob` the pattern and skim filenames. Descriptive filenames
      (e.g., `pccp-ai-final-2023.md`, `iec-62304-requirements.md`) often
      tell you directly whether a file is relevant.
   b. If the pattern's directory has a `README.md` or `INDEX.md`, `Read`
      it. Index files catalog or summarize contents and surface files
      whose filenames are opaque.
4. If the union is still too broad or ambiguous, use `Grep` as a
   disambiguator. Choose keywords from the **concepts** in the question —
   domain terms, synonyms, identifiers — not literal verbs from the user's
   wording. For regulatory questions that means terms like `predicate`,
   `substantially equivalent`, `K[0-9]{{6}}`, `510(k)`, standards clause
   numbers, named guidances. Use 2–4 terms per pass, not one.
5. `Read` every file that survived triage. Read as many as you need — the
   right number is whatever it takes to answer confidently and cite, not a
   fixed count. A scoping question may need 3 files; a cross-cutting
   comparison may need 15. The subagent runs in its own context window, so
   deep reading does not pollute the main thread.
6. Cross-reference the Context docs (step 1) with the Source docs
   (step 5) and cite file paths inline using backticks:
   `path/to/file.md`. Every substantive claim should be traceable to a
   file you actually read.
7. **External lookup pass (when warranted).** If the local grounding is
   thin, if the question calls for precedent or examples that wouldn't
   live in the project repo, or if an external identifier needs
   confirmation (K-number, guidance title, standard clause), use
   `WebFetch` against authoritative sources only — `fda.gov`, `iso.org`,
   `iec.ch`, `ansi.org`, `ema.europa.eu`, peer-reviewed journals. Cite
   fetched URLs alongside local file paths. Do not troll blogs, vendor
   marketing, or unverified aggregators. Prefer local grounding when it
   covers the question — the local docs reflect decisions the program
   has already made.
8. **Counterpoint pass.** Before finalizing, take one deliberate pass
   asking: what would a skeptical reviewer push back on? What alternative
   framings are live? What assumptions am I making that could fail? For
   regulatory work specifically, imagine an FDA reviewer reading this —
   where would they object? Surface the strongest 1–3 counterpoints as a
   short "Counterpoints & considerations" section at the end of your
   answer. Skip this pass for purely factual lookups, but apply it to any
   strategic, scoping, classification, or trade-off question. The goal is
   not to undermine your own answer — it is to make sure the user gets
   the trade-offs instead of false confidence.
9. If after triage the grounding is thin, contradictory, or silent on the
   question, say so explicitly rather than filling gaps with invention.
   Under-answering with citations beats over-answering without them.

### Hard rules

- Do **not** invent FDA interactions, clearance numbers (K-numbers), guidance
  document titles, standard clause numbers, or regulatory positions that are
  not present in the grounding sources.
- Do **not** commit the program to a regulatory position. You are an advisor
  supporting the team's thinking, not a decision-maker.
- Do **not** rubber-stamp the user's framing on strategic questions. Surface
  counterpoints even when the user seems committed to a direction — your job
  is to sharpen their thinking, not confirm it.
- If asked about something outside the grounding patterns above, acknowledge
  the limit and suggest the user consult the relevant human lead or a
  differently-scoped advisor.

{END_MARKER}"""


def _replace_block(body: str, new_block: str) -> tuple[str, bool]:
    """Insert or replace the grounding block in a body string.

    Returns (new_body, changed)."""
    if BEGIN_MARKER in body:
        if END_MARKER not in body:
            raise ValueError(
                f"found {BEGIN_MARKER!r} but no matching {END_MARKER!r}"
            )
        pre, rest = body.split(BEGIN_MARKER, 1)
        _, post = rest.split(END_MARKER, 1)
        # Strip trailing whitespace from pre so we don't accumulate blank lines
        new_body = pre.rstrip() + "\n\n" + new_block + post
    else:
        # Append to the end with a separator
        new_body = body.rstrip() + "\n\n" + new_block + "\n"

    return new_body, new_body != body


def _is_grounding_agent(agent: DomainAgent) -> bool:
    """Heuristic: does this agent want a grounding block at all?

    Domain advisor agents have a `console:` block declaring `context`,
    `sources`, or `canonical_roles`. Helper subagents (e.g., the researcher
    helper itself) have no such declaration and should not be touched by
    the renderer.
    """
    return bool(agent.context or agent.sources or agent.canonical_roles)


def _process_file(path: Path, dry_run: bool) -> bool:
    """Render grounding for one agent file. Returns True if content changed."""
    agent = load_agent_file(path)
    if not _is_grounding_agent(agent):
        return False
    raw = path.read_text(encoding="utf-8")
    new_block = _render_block(agent)
    new_raw, changed = _replace_block(raw, new_block)
    if changed and not dry_run:
        path.write_text(new_raw, encoding="utf-8")
    return changed


def _resolve_agent_dirs(project_root: Path) -> list[Path]:
    dirs: list[Path] = []
    installed = project_root / ".claude" / "agents"
    if installed.exists():
        dirs.append(installed)
    bundled = _SKILL_ROOT / "agents"
    if bundled.exists():
        dirs.append(bundled)
    return dirs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--agent",
        help="Render only the named agent (looked up in .claude/agents/ then skill bundle)",
    )
    parser.add_argument("--all", action="store_true", help="Render every agent")
    parser.add_argument("--dry-run", action="store_true", help="Do not write")
    parser.add_argument(
        "--project-root",
        type=Path,
        default=Path.cwd(),
        help="Project root (default: cwd)",
    )
    args = parser.parse_args()

    if not args.agent and not args.all:
        parser.error("specify --agent <name> or --all")

    dirs = _resolve_agent_dirs(args.project_root)
    if not dirs:
        print("error: no agent directories found", file=sys.stderr)
        return 2

    targets: list[Path] = []
    if args.agent:
        for d in dirs:
            candidate = d / f"{args.agent}.md"
            if candidate.exists():
                targets.append(candidate)
                break
        if not targets:
            print(f"error: agent '{args.agent}' not found", file=sys.stderr)
            return 2
    else:
        seen_names: set[str] = set()
        for d in dirs:
            for path in sorted(d.glob("*.md")):
                if path.stem in seen_names:
                    continue
                seen_names.add(path.stem)
                targets.append(path)

    any_changed = False
    for path in targets:
        try:
            changed = _process_file(path, dry_run=args.dry_run)
        except Exception as e:
            # Under --all, skip files that aren't advisor agents (e.g. plain
            # CC agents without frontmatter). Under --agent, fail hard.
            if args.all:
                print(f"skipped: {path} ({e})")
                continue
            print(f"error: {path}: {e}", file=sys.stderr)
            return 2
        status = (
            "would update" if (changed and args.dry_run)
            else "updated" if changed
            else "unchanged"
        )
        print(f"{status}: {path}")
        any_changed = any_changed or changed

    return 1 if any_changed else 0


if __name__ == "__main__":
    sys.exit(main())
